name: Continuous Testing - Drift Monitor

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight

jobs:
  monitor-drift:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pandas numpy

    - name: Run Drift Check
      run: |
        python monitor_drift.py